web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  environment:
    - MYSQL_HOST=db
    - MYSQL_USER=root
    - MYSQL_PASSWORD=foobaz
    - MYSQL_DATABASE=localdatabase
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=foobaz
    - MYSQL_DATABASE=localdatabase
